global-variables:
  - &default_cache_settings
    image: drillster/drone-volume-cache
    settings:
    volumes:
      - name: cache
        path: /cache
    when:
      ref:
        include:
          - refs/heads/feature/*
          - refs/heads/master
          - refs/heads/dev
          - refs/tags/*
      event:
        include:
          - push
          - pull_request
          - tag



kind: pipeline
type: docker
name: petclinic-frontend

volumes:
  - name: cache
    host:
      path: /tmp/cache

steps:
  - name: restore-cache
    <<: *default_cache_settings
    settings:
      restore: true
      mount:
        - ./docker

  - name: test
    image: node:10.23-alpine
    commands:
      - cd frontend && yarn install && yarn test

  - name: package
    image: node:10.23-alpine
    commands:
      - cd frontend && yarn install && yarn run dist

  - name: publish
    image: plugins/ecr
    settings:
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
      create_repository: true
      repo: harness-petclinic-frontend
      registry: 038062473746.dkr.ecr.us-east-1.amazonaws.com
      dockerfile: frontend/Dockerfile
      tags:
        - latest

  - name: rebuild-cache
    <<: *default_cache_settings
    settings:
      rebuild: true
      mount:
        - ./docker

---
global-variables:
  - &default_cache_settings
    image: drillster/drone-volume-cache
    settings:
    volumes:
      - name: cache
        path: /cache
    when:
      ref:
        include:
          - refs/heads/feature/*
          - refs/heads/master
          - refs/heads/dev
          - refs/tags/*
      event:
        include:
          - push
          - pull_request
          - tag


kind: pipeline
type: docker
name: petclinic-backend

volumes:
  - name: cache
    host:
      path: /tmp/cache

steps:
  - name: restore-cache
    <<: *default_cache_settings
    settings:
      restore: true
      mount:
        - ./docker
        - ./.m2

  - name: test
    image: openjdk:8u272-jdk
    commands:
    - cd backend && ./mvnw clean test

  - name: package
    image: openjdk:8u272-jdk
    commands:
      - cd backend && ./mvnw clean package -DskipTests

  - name: publish
    image: plugins/ecr
    settings:
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
      create_repository: true
      repo: harness-petclinic-backend
      registry: 038062473746.dkr.ecr.us-east-1.amazonaws.com
      dockerfile: backend/Dockerfile
      tags:
        - latest

  - name: rebuild-cache
    <<: *default_cache_settings
    settings:
      rebuild: true
      mount:
        - ./docker

