kind: pipeline
type: docker
name: petclinic-frontend

steps:
  - name: test
    image: node:10.23-alpine
    commands:
      - cd frontend && yarn install && yarn test

  - name: package
    image: node:10.23-alpine
    commands:
      - cd frontend && yarn install && yarn run dist
      - cp -r public/ /app/frontend/dist/


#  - name: publish
#    image: plugins/ecr
#    settings:
#      access_key:
#        from_secret: aws_access_key_id
#      secret_key:
#        from_secret: aws_secret_access_key
#      create_repository: true
#      repo: bar
#      registry: <account_id>.dkr.ecr.us-east-1.amazonaws.com
#      dockerfile: path/to/Dockerfile
#      tags:
#        - latest


#  deploy to k8



---
kind: pipeline
type: docker
name: petclinic-backend

steps:
  - name: test
    image: openjdk:8u272-jdk
    commands:
    - cd backend && ./mvnw clean test

  - name: package
    image: openjdk:8u272-jdk
    commands:
      - cd backend && ./mvnw clean package -DskipTests

  - name: publish
    image: plugins/ecr
    settings:
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
      create_repository: true
      repo: harness-petclinic-backend
      registry: 038062473746.dkr.ecr.us-east-1.amazonaws.com
      dockerfile: backend/Dockerfile
      tags:
        - latest



#  deploy to k8