kind: pipeline
type: docker
name: petclinic-graphql-backend

steps:
  - name: backend-test
    image: maven:3-jdk-8
    commands:
      - cd backend && ./mvnw clean test

#  trigger:
#    branch:
#      - master
#    event:
#      - push

---
kind: pipeline
type: docker
name: petclinic-graphql-frontend

steps:
  - name: backend-test
    image: node
    commands:
      - cd frontend && npm run test

#  trigger:
#    branch:
#      - master
#    event:
#      - push