kind: pipeline
type: docker
name: petclinic-graphql-backend

steps:
  - name: backend-test
    image: openjdk:8u272-jdk
    commands:
#    - cd backend && ./mvnw clean test
    - make backend-test

#  trigger:
#    branch:
#      - master
#    event:
#      - push

---
kind: pipeline
type: docker
name: petclinic-graphql-frontend

steps:
  - name: backend-test
    image: node
    commands:
    - cd frontend && npm run test

#  trigger:
#    branch:
#      - master
#    event:
#      - push