kind: pipeline
type: docker
name: petclinic-frontend

steps:
  - name: build&test
    image: node:10.23-alpine
    volumes:
      - name: dist
        path: /app/frontend/dist
    commands:
      - cd frontend && yarn install && yarn test
      - yarn run dist
      - cp -r public/ /app/frontend/dist/


  - name: volume sharing check
    image: alpine:latest
    volumes:
      - name: dist
        path: /app/frontend/dist
    commands:
      - ls -al /app/frontend/dist
#    trigger:
#      branch:
#        - master
#      event:
#        - push


#  - name: publish
#    image: plugins/ecr
#    settings:
#      access_key:
#        from_secret: aws_access_key_id
#      secret_key:
#        from_secret: aws_secret_access_key
#      create_repository: true
#      repo: bar
#      registry: <account_id>.dkr.ecr.us-east-1.amazonaws.com
#      dockerfile: path/to/Dockerfile
#      tags:
#        - latest


#  deploy to k8

volumes:
  - name: dist
    temp: {}


---
kind: pipeline
type: docker
name: petclinic-backend

steps:
  - name: test
    image: openjdk:8u272-jdk
    commands:
    - cd backend && ./mvnw clean test

#  trigger:
#    branch:
#      - master
#    event:
#      - push

#  - name: publish
#    image: plugins/ecr
#    settings:
#      access_key:
#        from_secret: aws_access_key_id
#      secret_key:
#        from_secret: aws_secret_access_key
#      create_repository: true
#      repo: bar
#      registry: <account_id>.dkr.ecr.us-east-1.amazonaws.com
#      dockerfile: path/to/Dockerfile
#      tags:
#        - latest


#  deploy to k8