kind: pipeline
type: docker
name: petclinic-graphql-backend

steps:
  - name: backend-test
    image: maven:3-jdk-8
    commands:
      - make backend-test

#  trigger:
#    branch:
#      - master
#    event:
#      - push

---
kind: pipeline
type: docker
name: petclinic-graphql-frontend

steps:
  - name: backend-test
    image: node
    commands:
      - make frontend-test

#  trigger:
#    branch:
#      - master
#    event:
#      - push