kind: pipeline
type: docker
name: petclinic-frontend

steps:
  - name: test
    image: node
    commands:
      - cd frontend && npm run test
#    trigger:
#      branch:
#        - master
#      event:
#        - push


#  - name: publish
#    image: plugins/ecr
#    settings:
#      access_key:
#        from_secret: aws_access_key_id
#      secret_key:
#        from_secret: aws_secret_access_key
#      create_repository: true
#      repo: bar
#      registry: <account_id>.dkr.ecr.us-east-1.amazonaws.com
#      dockerfile: path/to/Dockerfile
#      tags:
#        - latest


#  deploy to k8




---
kind: pipeline
type: docker
name: petclinic-backend

steps:
  - name: test
    image: openjdk:8u272-jdk
    commands:
    - cd backend && ./mvnw clean test

#  trigger:
#    branch:
#      - master
#    event:
#      - push

#  - name: publish
#    image: plugins/ecr
#    settings:
#      access_key:
#        from_secret: aws_access_key_id
#      secret_key:
#        from_secret: aws_secret_access_key
#      create_repository: true
#      repo: bar
#      registry: <account_id>.dkr.ecr.us-east-1.amazonaws.com
#      dockerfile: path/to/Dockerfile
#      tags:
#        - latest


#  deploy to k8